
[project]
nav = [
  { Overview = [
    { "CR26 Overview" = "index.md" },
    { "Deadlines and Milestones" = "deadlines-and-milestones.md" },
    { "Certification" = "certification.md" },
    { "Shared Responsibility Model" = "shared-responsibility-model.md" },
    { "Definitions" = "definitions.md" },
    { "Changelog" = "changelog.md" },
    { "Source Data" = "source-data.md" },
  ]},
  { Agencies = [
    { "Agency Home" = "agency/index.md" },
    { "FedRAMP's Role and Services" = "agency/fedramp-role-services.md" },
    { "Government-wide Collaboration" = "agency/government-wide-collaboration.md" },
    { "Getting Started" = "agency/getting-started.md" },
    { "Marketplace" = "agency/marketplace.md" },
    { "Accessing Packages" = "agency/accessing-packages.md" },
    { "Sponsorship" = "agency/sponsorship.md" },
    { "Certification Classes" = "agency/certification-classes.md" },
    { "Agency Responsibilities" = "agency/responsibilities.md" },
    { "Initial Authorization" = [
      { "Overview" = "agency/initial-authorization/index.md" },
      { "Additional Requirements" = "agency/initial-authorization/additional-requirements.md" },
      { "Low Controls" = "agency/initial-authorization/low-controls.md" },
      { "Moderate Controls" = "agency/initial-authorization/moderate-controls.md" },
      { "High Controls" = "agency/initial-authorization/high-controls.md" },
    ]},
    { "Ongoing Authorization" = [
      { "Overview" = "agency/ongoing-authorization/index.md" },
      { "Collaborative Continuous Monitoring" = "agency/ongoing-authorization/collaborative-continuous-monitoring.md" },
      { "Agency-Specific Continuous Monitoring" = "agency/ongoing-authorization/agency-specific-continuous-monitoring.md" },
    ]},
    { "Rev5" = [
      { "Overview" = "agency/rev5/index.md" },
      { "Authorization Tips" = "agency/rev5/authorization-tips.md" },
    ]},
    { "20x" = [
      { "Overview" = "agency/20x/index.md" },
      { "Authorization Tips" = "agency/20x/authorization-tips.md" },
    ]},
    { "Reporting Concerns" = "agency/reporting-concerns.md" },
    { "Legacy Materials" = "agency/legacy-materials.md" },
    { "Cybersecurity Directives" = "agency/cybersecurity-directives.md" },
  ]},
  { "Cloud Service Providers" = [
    { "Provider Home" = "provider/index.md" },
    { "FedRAMP's Role and Services" = "provider/fedramp-role-services.md" },
    { "Responsibilities" = "provider/responsibilities.md" },
    { "Getting Started" = [
      { "Overview" = "provider/getting-started/index.md" },
      { "Finding an Advisor" = "provider/getting-started/finding-an-advisor.md" },
      { "Choosing a Certification Type" = "provider/getting-started/choosing-a-certification-type.md" },
      { "Choosing a Certification Path" = "provider/getting-started/choosing-a-certification-path.md" },
      { "Choosing a Certification Class" = "provider/getting-started/choosing-a-certification-class.md" },
      { "Preparing and Getting Listed" = "provider/getting-started/preparing-and-getting-listed.md" },
      { "Implementing" = "provider/getting-started/implementing.md" },
      { "Finding an Assessor" = "provider/getting-started/finding-an-assessor.md" },
    ]},
    { "Rev5" = [
      { "Overview" = "provider/rev5/index.md" },
      { "Initial Certification" = [
        { "Overview" = "provider/rev5/initial-certification/index.md" },
        { "Class A" = "provider/rev5/initial-certification/class-a.md" },
        { "Class A Requirements" = "provider/rev5/initial-certification/class-a-requirements.md" },
        { "Class A Controls" = "provider/rev5/initial-certification/class-a-controls.md" },
        { "Class A Materials" = "provider/rev5/initial-certification/class-a-materials.md" },
        { "Class A Assessment" = "provider/rev5/initial-certification/class-a-assessment.md" },
        { "Class A Submission" = "provider/rev5/initial-certification/class-a-submission.md" },
        { "Class A Finalization" = "provider/rev5/initial-certification/class-a-finalization.md" },
        { "Class B" = "provider/rev5/initial-certification/class-b.md" },
        { "Class B Requirements" = "provider/rev5/initial-certification/class-b-requirements.md" },
        { "Class B Controls" = "provider/rev5/initial-certification/class-b-controls.md" },
        { "Class B Materials" = "provider/rev5/initial-certification/class-b-materials.md" },
        { "Class B Assessment" = "provider/rev5/initial-certification/class-b-assessment.md" },
        { "Class B Agency Review" = "provider/rev5/initial-certification/class-b-agency-review.md" },
        { "Class B Submission" = "provider/rev5/initial-certification/class-b-submission.md" },
        { "Class B Finalization" = "provider/rev5/initial-certification/class-b-finalization.md" },
        { "Class C" = "provider/rev5/initial-certification/class-c.md" },
        { "Class C Requirements" = "provider/rev5/initial-certification/class-c-requirements.md" },
        { "Class C Controls" = "provider/rev5/initial-certification/class-c-controls.md" },
        { "Class C Materials" = "provider/rev5/initial-certification/class-c-materials.md" },
        { "Class C Assessment" = "provider/rev5/initial-certification/class-c-assessment.md" },
        { "Class C Agency Review" = "provider/rev5/initial-certification/class-c-agency-review.md" },
        { "Class C Submission" = "provider/rev5/initial-certification/class-c-submission.md" },
        { "Class C Finalization" = "provider/rev5/initial-certification/class-c-finalization.md" },
        { "Class D" = "provider/rev5/initial-certification/class-d.md" },
        { "Class D Requirements" = "provider/rev5/initial-certification/class-d-requirements.md" },
        { "Class D Controls" = "provider/rev5/initial-certification/class-d-controls.md" },
        { "Class D Materials" = "provider/rev5/initial-certification/class-d-materials.md" },
        { "Class D Assessment" = "provider/rev5/initial-certification/class-d-assessment.md" },
        { "Class D Agency Review" = "provider/rev5/initial-certification/class-d-agency-review.md" },
        { "Class D Submission" = "provider/rev5/initial-certification/class-d-submission.md" },
        { "Class D Finalization" = "provider/rev5/initial-certification/class-d-finalization.md" },
      ]},
      { "Ongoing Certification" = [
        { "Class B/C/D Requirements" = "provider/rev5/ongoing-certification/class-b-c-d-requirements.md" },
        { "Class B/C/D Process" = "provider/rev5/ongoing-certification/class-b-c-d-process.md" },
      ]},
    ]},
    { "20x" = [
      { "Overview" = "provider/20x/index.md" },
      { "Initial Certification" = [
        { "Overview" = "provider/20x/initial-certification/index.md" },
        { "Class A" = "provider/20x/initial-certification/class-a.md" },
        { "Class A Requirements" = "provider/20x/initial-certification/class-a-requirements.md" },
        { "Class A Indicators" = "provider/20x/initial-certification/class-a-indicators.md" },
        { "Class A Materials" = "provider/20x/initial-certification/class-a-materials.md" },
        { "Class A Assessment" = "provider/20x/initial-certification/class-a-assessment.md" },
        { "Class A Submission" = "provider/20x/initial-certification/class-a-submission.md" },
        { "Class A Finalization" = "provider/20x/initial-certification/class-a-finalization.md" },
        { "Class B" = "provider/20x/initial-certification/class-b.md" },
        { "Class B Requirements" = "provider/20x/initial-certification/class-b-requirements.md" },
        { "Class B Indicators" = "provider/20x/initial-certification/class-b-indicators.md" },
        { "Class B Materials" = "provider/20x/initial-certification/class-b-materials.md" },
        { "Class B Assessment" = "provider/20x/initial-certification/class-b-assessment.md" },
        { "Class B Submission" = "provider/20x/initial-certification/class-b-submission.md" },
        { "Class B Finalization" = "provider/20x/initial-certification/class-b-finalization.md" },
        { "Class C" = "provider/20x/initial-certification/class-c.md" },
        { "Class C Requirements" = "provider/20x/initial-certification/class-c-requirements.md" },
        { "Class C Indicators" = "provider/20x/initial-certification/class-c-indicators.md" },
        { "Class C Materials" = "provider/20x/initial-certification/class-c-materials.md" },
        { "Class C Assessment" = "provider/20x/initial-certification/class-c-assessment.md" },
        { "Class C Submission" = "provider/20x/initial-certification/class-c-submission.md" },
        { "Class C Finalization" = "provider/20x/initial-certification/class-c-finalization.md" },
      ]},
    ]},
    { "Performance Management" = "provider/performance-management.md" },
    { "Additional Agency Requirements" = "provider/additional-agency-requirements.md" },
    { "Legacy Materials" = "provider/legacy-materials.md" },
  ]},
  { Assessors = [
    { "Assessor Home" = "assessor/index.md" },
    { "FedRAMP's Role and Services" = "assessor/fedramp-role-services.md" },
    { "Getting Started" = "assessor/getting-started.md" },
    { "Recognition" = "assessor/recognition.md" },
    { "Marketplace Listing" = "assessor/marketplace-listing.md" },
    { "Rev5" = [
      { "Overview" = "assessor/rev5/index.md" },
      { "Performance Standards" = "assessor/rev5/performance-standards.md" },
      { "Initial Certification" = [
        { "Overview" = "assessor/rev5/initial-certification/index.md" },
        { "Class A" = "assessor/rev5/initial-certification/class-a.md" },
        { "Class A Materials" = "assessor/rev5/initial-certification/class-a-materials.md" },
        { "Class B" = "assessor/rev5/initial-certification/class-b.md" },
        { "Class B Materials" = "assessor/rev5/initial-certification/class-b-materials.md" },
        { "Class C" = "assessor/rev5/initial-certification/class-c.md" },
        { "Class C Materials" = "assessor/rev5/initial-certification/class-c-materials.md" },
        { "Class D" = "assessor/rev5/initial-certification/class-d.md" },
        { "Class D Materials" = "assessor/rev5/initial-certification/class-d-materials.md" },
      ]},
      { "Ongoing Certification" = [
        { "Overview" = "assessor/rev5/ongoing-certification/index.md" },
        { "Class A" = "assessor/rev5/ongoing-certification/class-a.md" },
        { "Class A Materials" = "assessor/rev5/ongoing-certification/class-a-materials.md" },
        { "Class B" = "assessor/rev5/ongoing-certification/class-b.md" },
        { "Class B Materials" = "assessor/rev5/ongoing-certification/class-b-materials.md" },
        { "Class C" = "assessor/rev5/ongoing-certification/class-c.md" },
        { "Class C Materials" = "assessor/rev5/ongoing-certification/class-c-materials.md" },
        { "Class D" = "assessor/rev5/ongoing-certification/class-d.md" },
        { "Class D Materials" = "assessor/rev5/ongoing-certification/class-d-materials.md" },
      ]},
    ]},
    { "20x" = [
      { "Overview" = "assessor/20x/index.md" },
      { "Performance Standards" = "assessor/20x/performance-standards.md" },
      { "Initial Certification" = [
        { "Overview" = "assessor/20x/initial-certification/index.md" },
        { "Class A" = "assessor/20x/initial-certification/class-a.md" },
        { "Class B" = "assessor/20x/initial-certification/class-b.md" },
        { "Class C" = "assessor/20x/initial-certification/class-c.md" },
        { "Class D" = "assessor/20x/initial-certification/class-d.md" },
      ]},
      { "Ongoing Certification" = [
        { "Overview" = "assessor/20x/ongoing-certification/index.md" },
        { "Class A" = "assessor/20x/ongoing-certification/class-a.md" },
        { "Class B" = "assessor/20x/ongoing-certification/class-b.md" },
        { "Class C" = "assessor/20x/ongoing-certification/class-c.md" },
        { "Class D" = "assessor/20x/ongoing-certification/class-d.md" },
      ]},
    ]},
    { "Performance Management" = "assessor/performance-management.md" },
    { "Legacy Materials" = "assessor/legacy-materials.md" },
  ]},
  { Advisors = [
    { "Advisor Home" = "advisor/index.md" },
    { "FedRAMP's Role and Services" = "advisor/fedramp-role-services.md" },
    { "Getting Started" = "advisor/getting-started.md" },
    { "Marketplace Listing" = "advisor/marketplace-listing.md" },
  ]},
  { "--> return to FedRAMP.gov" = "/" },
]

site_name = "FedRAMP Consolidated Rules for 2026"
site_description = "A description."
site_author = "pete@fedramp.gov"
site_dir = "docs/"
docs_dir = "markdown/"
site_url = "https://fedramp.gov/2026/"
repo_url = "https://github.com/fedramp/consolidated-rules-2026"
repo_name = "FedRAMP/consolidated-rules-2026"
extra_css = ["stylesheets/custom.css"]
copyright = "fedramp.gov"

[project.extra]
homepage = "/2026"
generator = false

[project.extra.tags]
Rev5 = "rev5"
20x = "20x"

[project.theme]
custom_dir = "overrides"
logo = "assets/fr-only-logo-black.png"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.top",
    "navigation.tracking",
    # "navigation.tabs",
    #"navigation.expand",
    "navigation.path",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.theme.icon.tag]
rev5 = "material/numeric-5-circle-outline"
20x = "material/alpha-x-circle-outline"

[project.theme.icon.admonition]
abstract = "fontawesome/solid/gavel"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
tables = {}

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
